### ISSUE TITLE
Error on game startup after adding the mod

### ISSUE THREAD

**Issue by DofD10** [raiguard/Factorio-BottleneckLite#1]
Hey there
Getting the following error on game startup:
```
61.072 Error ModManager.cpp:1574: Fehler beim Laden der Mod „BottleneckLite“: __BottleneckLite__/data-final-fixes.lua:24: attempt to index local 'selection_box' (a nil value)
stack traceback:
	__BottleneckLite__/data-final-fixes.lua:24: in function 'build_indicator
	__BottleneckLite__/data-final-fixes.lua:73: in function 'add_to_wv
	__BottleneckLite__/data-final-fixes.lua:85: in main chunk
```

Cheers

**Comment by raiguard** [comment]
Can you please provide a save game that I can sync mods with? It can be a new save, just remove BNL, create a new save, then attach that.

**Comment by DofD10** [comment]
This actually happens at normal game startup. Not when loading the save game and syncing mods with it ;)

**Comment by raiguard** [comment]
I know. That's why I said to remove BNL. I need to be able to get all of the other mods you're using so I can reproduce the issue. :)

**Comment by DofD10** [comment]
[BNL test.zip](https://github.com/raiguard/Factorio-BottleneckLite/files/6786739/BNL.test.zip)
There you go :)

**Comment by raiguard** [comment]
Thanks, fixed for the next version.

**Comment by DofD10** [comment]
Thanks mate!
