### ISSUE TITLE
Disabled certain indicators

### ISSUE THREAD

**Issue by Tsunayoshi** [raiguard/Factorio-BottleneckLite#12]
Hello,
since the change to colors, i am missing the option to disable specific indicators. Like as example, when a machine is working fine, i do not want to see any indicator, same as full output. These things are fine to me and do not need any color (i also do not want green indicators, because i only want to see them if something is wrong. Else i want to keep it close to the basegame without a symbol)
I tried to put the alpha on 0. The color went black but this is fully ignored. It shown as i never changed a thing.

Hope you can change it in a way that 0 Alpha removes them.

**Comment by raiguard** [comment]
0 alpha should have been removing them, turns out I forgot to premul the color before applying it. So you had to set all sliders to zero. I am putting out a patch to fix this and make the behavior more predictable.
