### ISSUE TITLE
Incorrect icon during output full

### ISSUE THREAD

**Issue by Moremackles** [raiguard/Factorio-BottleneckLite#13]
Based on other posts I assume that this might be an engine limitation since you're just reading the animation state, but to clear it up; Is this possible to fix? 
![image](https://github.com/raiguard/BottleneckLite/assets/34537855/7c2ca631-451a-4450-869f-faf172110a6c)
Thanks for your contributions regardless.

**Comment by raiguard** [comment]
As you can see, the status in the GUI is also wrong, so this is a base game issue.

**Comment by Moremackles** [comment]
Ah, I failed to notice that. Thanks.
