### ISSUE TITLE
Glowing Indicators

### ISSUE THREAD

**Issue by Identifier** [raiguard/Factorio-BottleneckLite#14]
Been loving this mod ever since 1.1.  Now I'm coming back to Factorio for 2.0 and I'm glad to see you quickly updated this mod for 2.0.  Thanks!  I don't remember how "Glowing indicators" are supposed to look at night, but at least in 2.0 it doesn't seem to look any different whether they're checked or unchecked.  Here's a screenshot.  You can see the bottleneck indicator on the last furnace in the line is just a little brighter than the others, but that's because the flashlight from the engineer is shining on it slightly.  
![Screenshot 2024-10-23 111330](https://github.com/user-attachments/assets/10e918bf-f6f9-4d6c-9d0c-7ca570ff0b26)

**Comment by minimusubi** [comment]
This is how they used to look, as shown in the preview of an pre-2.0 save
![image](https://github.com/user-attachments/assets/bbcacfe2-fe0b-4596-a634-10adce8b8093)

**Comment by Identifier** [comment]
Looks like something in 2.0 changed it then.
