### ISSUE TITLE
Error with latest update 10/29 MST

### ISSUE THREAD

**Issue by StephJ2Fan** [raiguard/Factorio-BottleneckLite#16]
![image](https://github.com/user-attachments/assets/db7d30ff-e81d-43b3-8859-dffab48ce3bf)

After updating to the latest version, I recieved this error message.  If you need more info just let me know.
Factorio SA version 2.0.12
BN Lite version 1.3.1

**Comment by Timakrisz** [comment]
Same here. :(

**Comment by serjevski** [comment]
Same here

__BottleneckLite__/data-final-fixes.lua:115: attempt to index field 'graphics_set' (a nil value)
stack traceback:
	__BottleneckLite__/data-final-fixes.lua:115: in main chunk
