### ISSUE TITLE
Add electricity symbol for low power

### ISSUE THREAD

**Issue by Layarion** [raiguard/Factorio-BottleneckLite#3]
Instead of having a circle for low power, i'd like to see a lightning bolt looking thing. Yellow lightning bolt for low power, and red for no power.

If electricity get's it's own symbol, then I don't have to give it it's own color (like purple) to be able to tell what's wrong.

**Comment by raiguard** [comment]
Unfortunately, this isn't possible due to game engine limitations. Sorry.
