### ISSUE TITLE
Give priority to certain warnings

### ISSUE THREAD

**Issue by Layarion** [raiguard/Factorio-BottleneckLite#4]
I have no/low power set to the color purple. When power is low though, I don't always see purple because it's overridden by the colors set for full output. I'd like to let low/no power take precedence.

**Comment by raiguard** [comment]
Unfortunately, this isn't possible because the game itself prioritizes the "full output" status over the "low power" status. BNL does everything during game startup and has no control over how it behaves at runtime.
