### ISSUE TITLE
Colorblind Accommodation

### ISSUE THREAD

**Issue by FunkyDe** [raiguard/Factorio-BottleneckLite#5]
If possible, can you change the green color to a darker green or add a dark green option? Although I am not extremely red-green colorblind, it's often hard to tell the difference between working and idle machines under the default settings. I know that there is the option to change the light green to other colors, but it would be nice.

**Comment by raiguard** [comment]
The color settings are now freely customizable instead of being limited to a predefined selection.
![image](https://github.com/raiguard/BottleneckLite/assets/3515394/6a6c7abb-fbb2-47b4-8ed6-b1a6f234307e)
