### ISSUE TITLE
Updating from 1.2.4 to 1.2.5 resets mod settings

### ISSUE THREAD

**Issue by Krotain** [raiguard/Factorio-BottleneckLite#7]
When I updated this mod from 1.2.4 to 1.2.5 all mod settings were reset. Attempting to load a save brings up the sync mods screen but fails to restore mod settings properly. Downgrading back to 1.2.4 allows it to restore the startup settings. I was able to update to 1.2.5 and manually set everything back to what it was before with no issue.

**Comment by raiguard** [comment]
Yes, this is expected. The settings have changed their fundamental type and there isn't a way to automatically migrate them. I'm sorry.

**Comment by raiguard** [comment]
I misunderstood what you said, it shouldn't be resetting _all_ settings. That is a bug in the base game and has been fixed for 1.1.83.
https://forums.factorio.com/106445
I will pull this release off the mod portal to prevent further damage.
