### ISSUE TITLE
The last update broke all my mod settings!

### ISSUE THREAD

**Issue by Dominiquini** [raiguard/Factorio-BottleneckLite#8]
When I updated this mod to version 1.2.5, my saved game was broken with all settings reseted!

Look at the difference on the log:

1.2.4:
[factorio-previous.log](https://github.com/raiguard/BottleneckLite/files/11655196/factorio-previous.log)

1.2.5:
[factorio-current.log](https://github.com/raiguard/BottleneckLite/files/11655198/factorio-current.log)

Maybe this line will help:

> 3.680 Error GlobalModSettings.cpp:161: Failed to read mod settings: Unsupported color format. Expected a list of 4 values { r, g, b, a } or a dictionary { r = ..., g = ..., b = ..., a = ... }.

Thanks

**Comment by Dominiquini** [comment]
I see that you change the settings type (string-setting -> color-setting), but maintain the same name. Maybe you need to implement some migration!

Thanks.

**Comment by raiguard** [comment]
Duplicate of #7. There's no way to migrate these that I know of.

**Comment by raiguard** [comment]
Oh, my bad, I misunderstood the issue. This has been fixed for Factorio 1.1.83.
https://forums.factorio.com/106445
